--part - 5


--Find the top 3 bestselling books (highest quantity sold).
SELECT TOP 3
    b.title AS book_title,
    SUM(o.quantity) AS total_sold
FROM Orders o
JOIN Books b
ON o.book_id = b.book_id
GROUP BY b.title
ORDER BY total_sold DESC;

--List authors who have more than 2 books in the database.
SELECT a.name ,COUNT(b.book_id) AS total_books
FROM Authors a
JOIN Books b
ON a.author_id = b.author_id
GROUP BY a.name
HAVING COUNT(b.book_id) > 2;

--Display customers who never placed an order.
SELECT  c.customer_id,c.name
FROM Customers c
LEFT JOIN Orders o
ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


--Show the total revenue generated by each author.

SELECT a.name ,SUM(o.quantity * b.price) AS total_revenue
FROM Authors a
JOIN Books b
ON a.author_id = b.author_id
JOIN Orders o
ON b.book_id = o.book_id
GROUP BY a.name;


--Create views for:

--Books and their available stock.
CREATE VIEW vw_books_stock AS
SELECT book_id,title,stock
FROM Books;


SELECT * FROM vw_books_stock;

--Orders with customer names and book titles.
CREATE VIEW vw_orders_details AS
SELECT o.order_id,c.name AS customer_name,b.title AS book_title,o.quantity,o.order_date
FROM Orders o
JOIN Customers c
ON o.customer_id = c.customer_id
JOIN Books b
ON o.book_id = b.book_id;

SELECT * FROM vw_orders_details;